### XGBoost for multiclass clasification

In [2]:
from sklearn.datasets import make_multilabel_classification
import numpy as np

import xgboost as xgb

# Make a synthetic ranking dataset for demonstration
seed = 1994
X, y = make_multilabel_classification(n_samples=10000, n_features=64, n_classes=100, n_labels=100, length=64, random_state=seed)

In [53]:
clf = xgb.XGBClassifier(tree_method="hist", multi_strategy="multi_output_tree")
clf.fit(X, y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy='multi_output_tree',
              n_estimators=None, n_jobs=None, num_parallel_tree=None, ...)

In [54]:
np.testing.assert_allclose(clf.predict(X), y, rtol=0, atol=1)

In [55]:
scores = clf.predict(X)
scores

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 0., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 0., 1., ..., 1., 1., 1.],
       [1., 0., 1., ..., 1., 1., 1.],
       [1., 0., 1., ..., 1., 1., 1.]], shape=(10000, 100))

In [31]:
X

array([[1., 1., 1., ..., 1., 1., 1.],
       [0., 2., 1., ..., 4., 0., 0.],
       [0., 1., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 1., ..., 3., 0., 0.],
       [1., 3., 1., ..., 0., 2., 1.],
       [1., 1., 0., ..., 3., 0., 1.]], shape=(10000, 64))

In [35]:
y[:10]

array([[1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0,
        1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1,

In [3]:
scores

NameError: name 'scores' is not defined

### XGboost for ranking

In [5]:
from sklearn.datasets import make_classification
import numpy as np

import xgboost as xgb

In [40]:
# Make a synthetic ranking dataset for demonstration
seed = 1994
X, y = make_classification(random_state=seed, n_samples=13000, n_classes=1000, n_features=128, n_clusters_per_class=1, n_informative=10)
rng = np.random.default_rng(seed)
n_query_groups = 130
qid = rng.integers(0, n_query_groups, size=X.shape[0])

In [41]:
# Sort the inputs based on query index
sorted_idx = np.argsort(qid)
X = X[sorted_idx, :]
y = y[sorted_idx]
qid = qid[sorted_idx]

In [42]:
ranker = xgb.XGBRanker(tree_method="hist", lambdarank_num_pair_per_sample=100, objective="rank:ndcg", lambdarank_pair_method="topk", ndcg_exp_gain=False, n_jobs=32)
ranker.fit(X, y, qid=qid)

XGBRanker(base_score=None, booster=None, callbacks=None, colsample_bylevel=None,
          colsample_bynode=None, colsample_bytree=None, device=None,
          early_stopping_rounds=None, enable_categorical=False,
          eval_metric=None, feature_types=None, feature_weights=None,
          gamma=None, grow_policy=None, importance_type=None,
          interaction_constraints=None, lambdarank_num_pair_per_sample=100,
          lambdarank_pair_method='topk', learning_rate=None, max_bin=None,
          max_cat_threshold=None, max_cat_to_onehot=None, max_delta_step=None,
          max_depth=None, max_leaves=None, min_child_weight=None, missing=nan,
          monotone_constraints=None, multi_strategy=None, n_estimators=None, ...)

In [43]:
scores = ranker.predict(X)
sorted_idx = np.argsort(scores)[::-1]
scores = scores[sorted_idx]

In [44]:
y[sorted_idx]

array([921, 964, 931, ..., 222,  37,  89], shape=(13000,))

In [46]:
X[sorted_idx]

array([[-1.99623467, -1.60066491, -1.14859619, ...,  0.97622371,
         0.03855759, -0.6706524 ],
       [ 0.00720818,  0.46201922,  0.20007459, ...,  0.86878796,
        -0.49035051,  0.22715568],
       [-0.92678517, -0.88739992, -0.31044303, ..., -0.95662015,
         1.16699195, -0.87611814],
       ...,
       [ 0.93864637,  1.5977829 ,  0.65987914, ...,  1.2271438 ,
         0.7651621 , -1.50627444],
       [ 1.86243412,  0.86987035, -1.7779142 , ..., -0.43754556,
        -0.5301248 , -0.74365196],
       [ 2.03081958,  1.19450573,  1.28582164, ...,  0.2144459 ,
         0.10511468, -0.62302539]], shape=(13000, 128))

In [49]:
import polars as pl
pl.read_parquet("user_embeddings_checkpoints/user_classes_checkpoint_10000.parquet")

shape: (10_000, 129)
┌───────────┬──────────┬──────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ user_id   ┆ 0        ┆ 1        ┆ 2        ┆ … ┆ 124      ┆ 125      ┆ 126      ┆ 127      │
│ ---       ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ u32       ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞═══════════╪══════════╪══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 289340968 ┆ 0.009508 ┆ 0.008891 ┆ 0.011923 ┆ … ┆ 0.007554 ┆ 0.009235 ┆ 0.006205 ┆ 0.009471 │
│ 425277009 ┆ 0.008624 ┆ 0.008808 ┆ 0.014256 ┆ … ┆ 0.008797 ┆ 0.009919 ┆ 0.007015 ┆ 0.008722 │
│ 142975948 ┆ 0.01011  ┆ 0.008743 ┆ 0.012185 ┆ … ┆ 0.009537 ┆ 0.009418 ┆ 0.007246 ┆ 0.008156 │
│ 312217955 ┆ 0.011273 ┆ 0.008195 ┆ 0.013888 ┆ … ┆ 0.010035 ┆ 0.010922 ┆ 0.006945 ┆ 0.009624 │
│ 421832753 ┆ 0.009773 ┆ 0.008709 ┆ 0.012444 ┆ … ┆ 0.007505 ┆ 0.008635 ┆ 0.006358 ┆ 0.008614 │
│ …         ┆ …        ┆ …        ┆ …        ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ 491933285 ┆ 0.010054 ┆ 0.00889  ┆ 0.012297 ┆ … ┆ 0.009954 ┆ 0.010572 ┆ 0.006647 ┆ 0.009027 │
│ 163240682 ┆ 0.010371 ┆ 0.009397 ┆ 0.013355 ┆ … ┆ 0.010121 ┆ 0.009467 ┆ 0.006525 ┆ 0.010382 │
│ 106462495 ┆ 0.009774 ┆ 0.008913 ┆ 0.01351  ┆ … ┆ 0.007968 ┆ 0.010667 ┆ 0.007209 ┆ 0.008007 │
│ 226258928 ┆ 0.009886 ┆ 0.008558 ┆ 0.011858 ┆ … ┆ 0.009298 ┆ 0.010038 ┆ 0.006405 ┆ 0.009662 │
│ 140705684 ┆ 0.009714 ┆ 0.00839  ┆ 0.012903 ┆ … ┆ 0.00836  ┆ 0.009198 ┆ 0.005916 ┆ 0.008722 │
└───────────┴──────────┴──────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘